# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\".\n\nAddRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x02\x12\x0f\n\x07number2\x18\x02 \x01(\x02\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x02\"3\n\x0fMultiplyRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x02\x12\x0f\n\x07number2\x18\x02 \x01(\x02\"\"\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\x8b\x01\n\nCalculator\x12\x36\n\x03\x41\x64\x64\x12\x16.calculator.AddRequest\x1a\x17.calculator.AddResponse\x12\x45\n\x08Multiply\x12\x1b.calculator.MultiplyRequest\x1a\x1c.calculator.MultiplyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=32
  _globals['_ADDREQUEST']._serialized_end=78
  _globals['_ADDRESPONSE']._serialized_start=80
  _globals['_ADDRESPONSE']._serialized_end=109
  _globals['_MULTIPLYREQUEST']._serialized_start=111
  _globals['_MULTIPLYREQUEST']._serialized_end=162
  _globals['_MULTIPLYRESPONSE']._serialized_start=164
  _globals['_MULTIPLYRESPONSE']._serialized_end=198
  _globals['_CALCULATOR']._serialized_start=201
  _globals['_CALCULATOR']._serialized_end=340
# @@protoc_insertion_point(module_scope)
